<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance as Middleware;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Tightenco\Ziggy\Ziggy;

class Store extends Middleware
{

    public function handle($request, Closure $next)
    {
        $store = $request->route('store');
        auth()->user()->useStore($store);

        $request->attributes->add(['store' => auth()->user()->getCurrentStore()]);

        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }


}
